from __future__ import annotations

import pytest

from proligent.model import Document
from test.test_mocks import mock_uuid_sequence


def test_document_build_with_explicit_identifier() -> None:
    """Test that build uses the provided identifier."""
    doc_id = "D0C0601D-0000-0000-0000-000000000001"
    doc = Document(
        file_name="Report.pdf",
        identifier=doc_id
    )
    assert doc.suggested_document_file_name == f"Document_{doc_id}_Report.pdf"

    document_type = doc.build()
    assert document_type.identifier == doc_id
    assert document_type.file_name == "Report.pdf"


def test_document_build_with_auto_generated_identifier() -> None:
    """Test that build auto-generates identifier if not provided."""
    with mock_uuid_sequence():
        doc = Document(
            file_name="ReportLogs.txt"
        )

        generated_identifier = doc.identifier
        assert doc.suggested_document_file_name == f"Document_{generated_identifier}_ReportLogs.txt"

        document_type = doc.build()
        # Should use sequential UUID from mock
        assert document_type.identifier == "00000000-0000-0000-0000-000000000001"
        assert document_type.file_name == "ReportLogs.txt"


def test_document_build_with_various_extensions() -> None:
    """Test that build works with various file extensions."""
    doc_id = "D0C0601D-0000-0000-0000-000000000002"

    extensions = [".pdf", ".zip", ".txt", ".docx", ".xml", ".json", ".csv"]
    for ext in extensions:
        doc = Document(
            file_name=f"File{ext}",
            identifier=doc_id
        )
        assert doc.suggested_document_file_name == f"Document_{doc_id}_File{ext}"

        document_type = doc.build()
        assert document_type.identifier == doc_id
        assert document_type.file_name == f"File{ext}"


def test_document_build_with_name_and_description() -> None:
    """Test that build includes name and description when provided."""
    doc_id = "D0C0601D-0000-0000-0000-000000000003"
    doc = Document(
        file_name="Report.pdf",
        identifier=doc_id,
        name="Test Report",
        description="This is a test report"
    )

    document_type = doc.build()
    assert document_type.identifier == doc_id
    assert document_type.name == "Test Report"
    assert document_type.description == "This is a test report"


def test_document_suggested_document_file_name() -> None:
    """Test the suggested_document_file_name property."""
    doc_id = "D0C0601D-0000-0000-0000-000000000004"
    doc = Document(
        file_name="TestFile.pdf",
        identifier=doc_id
    )

    suggested_name = doc.suggested_document_file_name
    assert suggested_name == f"Document_{doc_id}_TestFile.pdf"


def test_document_suggested_document_file_name_with_auto_guid() -> None:
    """Test that suggested_document_file_name auto-generates GUID if not provided."""
    with mock_uuid_sequence():
        doc = Document(
            file_name="AutoGenerated.pdf"
        )

        suggested_name = doc.suggested_document_file_name
        assert suggested_name == "Document_00000000-0000-0000-0000-000000000001_AutoGenerated.pdf"


def test_document_multiple_builds_use_same_identifier() -> None:
    """Test that calling build() multiple times on the same Document generates a new GUID each time if identifier is not set."""
    with mock_uuid_sequence():
        doc = Document(
            file_name="Report.pdf"
        )

        # First build
        document_type1 = doc.build()
        assert document_type1.identifier == "00000000-0000-0000-0000-000000000001"

        # Second build - should get next sequential UUID
        document_type2 = doc.build()
        assert document_type2.identifier == "00000000-0000-0000-0000-000000000001"


def test_document_with_explicit_identifier_stays_constant() -> None:
    """Test that explicit identifier remains the same across multiple builds."""
    doc_id = "D0C0601D-0000-0000-0000-000000000005"
    doc = Document(
        file_name="Report.pdf",
        identifier=doc_id
    )

    # Multiple builds should use the same identifier
    document_type1 = doc.build()
    document_type2 = doc.build()

    assert document_type1.identifier == doc_id
    assert document_type2.identifier == doc_id


def test_document_case_insensitive_guid() -> None:
    """Test that build works with mixed case GUIDs."""
    doc_id_lower = "d0c0601d-0000-0000-0000-000000000008"
    doc = Document(
        file_name="Report.pdf",
        identifier=doc_id_lower
    )

    document_type = doc.build()
    assert document_type.identifier == doc_id_lower

    doc_id_upper = "D0C0601D-AAAA-BBBB-CCCC-000000000009"
    doc = Document(
        file_name="_Report.pdf",
        identifier=doc_id_upper
    )

    document_type = doc.build()
    assert document_type.identifier == doc_id_upper


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
